In [9]:
import cv2
import numpy as np

In [12]:
face_classifier = cv2.CascadeClassifier('C:/Users/admin/Anaconda3/Lib/site-packages/cv2/data/haarcascade_frontalface_alt.xml')
def face_extractor(img):
    gray = cv2.cvtColor(img,cv2.COLOR_BGR2GRAY)
    faces = face_classifier.detectMultiScale(gray,1.3,5)
    
    if faces is():
        return None
    
    for(x,y,w,h) in faces:
        cropped_face = img[y:y+h,x:x+w]
        
        return cropped_face
    
    
    
    

cap = cv2.VideoCapture(0)
count = 0

while True:
    ret,frame = cap.read()
    if face_extractor(frame) is not None:
        count+=1
        face = cv2.resize(face_extractor(frame),(200,200))
        face = cv2.cvtColor(face,cv2.COLOR_BGR2GRAY)
        
        file_name_path = 'E:/ml/IMAGES_EG/'+'Zeel'+str(count)+'.jpg'
        cv2.imwrite(file_name_path,face)
        
        
        cv2.putText(face,str(count),(50,50),cv2.FONT_HERSHEY_COMPLEX,1,(0,255,0),2)
        cv2.imshow('Face Copper',face)

        

    else:
        print("Face not Found")
        pass 

    if cv2.waitKey(1)==13 or count==100:
        break
        
        
cap.release()
cv2.destroyAllWindows()
print('Collecting Samples Complete!!!')



Face not Found
Face not Found
Face not Found


SyntaxError: invalid syntax (<ipython-input-9-04224fc6e986>, line 2)

In [6]:
import cv2
import numpy as np
from os import listdir
from os.path import isfile,join


data_path='E:/ml/IMAGES_EG/'
onlyfiles =[f for f in listdir(data_path) if isfile(join(data_path,f))]
Training_Data,Labels= [],[]
for i,files in enumerate(onlyfiles):
    image_path = data_path + onlyfiles[i]
    images = cv2.imread(image_path, cv2.IMREAD_GRAYSCALE)
    Training_Data.append(np.asarray(images, dtype=np.uint8))
    Labels.append(i)
    
Labels=np.asarray(Labels,dtype=np.int32)
model=cv2.face.LBPHFaceRecognizer_create()
model=cv2.face.LBPHFaceRecognizer_create()
model.train(np.asarray(Training_Data), np.asarray(Labels))
print("model Training Complete!!!!!!!!")
#print(model)
#print(Labels)

model Training Complete!!!!!!!!


In [7]:
face_classifier = cv2.CascadeClassifier('C:/Users/admin/Anaconda3/Lib/site-packages/cv2/data/haarcascade_frontalface_alt.xml')

def face_detector (img, size=0.5):
    gray = cv2.cvtColor(img,cv2.COLOR_BGR2GRAY)
    faces = face_classifier.detectMultiScale(gray,1.3,5)
    
    if faces is():
        return img,[]
    
    
    for(x,y,w,h) in faces:
        cv2.rectangle(img,(x,y),(x+w,y+h),(0,255,255),2)
        roi = img[y:y+h, x:x+w]
        roi = cv2.resize(roi,(200,200))
        return img,roi
    
    
cap = cv2.VideoCapture(0)
while True:
    
    ret,frame = cap.read()
    image,face = face_detector(frame)
    
    try:
        face = cv2.cvtColor(face, cv2.COLOR_BGR2GRAY)
        result = model.predict(face)
        print(*result)
        print(result[0])
        
        if result[1] < 500:
            confidence = int(100*(1-(result[1])/300))
            display_string = str(confidence)+'% Confidencit is user'

        cv2.putText(image,display_string,(100,120), cv2.FONT_HERSHEY_COMPLEX,1,(250,120,255),2) 
        if confidence < 85:
            cv2.putText(image, "Unblocked", (250,450), cv2.FONT_HERSHEY_COMPLEX,1,(0,255,0),2)
            cv2.imshow('Face Cropper', image)
    
        else :
            cv2.putText(image, "Locked", (250,450), cv2.FONT_HERSHEY_COMPLEX,1,(0,255,0),2)
            cv2.imshow('Face Cropper', image)
    
    except:
        cv2.putText(image, "Face Not Found", (250,450), cv2.FONT_HERSHEY_COMPLEX,1,(0,255,0),2)
    
        cv2.imshow('Face Cropper', image)
        pass
    
    
    if cv2.waitKey(1)==13:
        break
        
cap.release()
cv2.destroyAllWindows()


164 42.365872175193864
164
152 42.33720050005698
152
159 42.19498351293103
159
160 43.18582061079918
160
148 42.1639926692837
148
151 42.70837908925811
151
105 42.90705098731145
105
105 42.2813931526548
105
160 41.77099671220512
160
178 42.67431595507482
178
151 42.82323417482554
151
151 42.68164376826764
151
105 42.78516433002035
105
105 42.47470588483857
105
151 42.8903804691908
151
151 42.84810064666851
151
105 42.561139454053425
105
148 42.58055659547044
148
178 43.151441487901714
178
105 43.24218004698436
105
161 43.150235347371066
161
112 42.4467452185753
112
160 42.30273493033807
160
100 43.01059873104581
100
160 45.33156053315848
160
100 44.036397711365815
100
160 44.39192482526742
160
160 46.01587736323539
160
160 45.856458827069375
160
100 43.89096105627401
100
160 44.81586019990186
160
100 45.3874194110731
100
100 46.32758006143182
100
100 44.71262099519491
100
100 43.91860694083334
100
100 44.06853948053143
100
160 44.12841957656804
160
100 44.98295585321538
100
160 43.3218

In [8]:
import cv2

In [4]:
img = cv2.imread("E:/ml/IMAGES_EG/Kshitij14.jpg",0)
print(img)

[[183 149  81 ...  18  18  17]
 [172 125  66 ...  17  16  16]
 [161  92  46 ...  16  16  17]
 ...
 [ 26  25  24 ...  25  43  70]
 [ 23  25  24 ...  21  31  40]
 [ 23  25  23 ...  24  32  43]]


In [9]:
import numpy as np
img = cv2.imread("E:/ml/IMAGES_EG/Kshitij15.jpg",0)
np_img = np.array(img)
print(np_img)

[[49 30 27 ... 13 11 10]
 [34 22 21 ... 10 10  9]
 [27 23 28 ...  9  9 10]
 ...
 [28 26 23 ... 28 29 32]
 [28 27 25 ... 31 30 27]
 [31 31 28 ... 29 27 20]]
